project_id = "lhcjucaevoouqozihzpv"

[functions.send-reservation-email]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-receipt-pdf]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.create-mercado-pago-payment]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.mercadopago-checkout]
verify_jwt = false

[functions.create-order-mp]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.create-card-payment]
verify_jwt = false

[functions.mp-public-config]
verify_jwt = false

[functions.fetch-google-reviews]
verify_jwt = false

[functions.send-checkin-email]
verify_jwt = false

[functions.send-checkout-email]
verify_jwt = false

[functions.send-internal-feedback]
verify_jwt = false

[functions.cron-guest-emails]
verify_jwt = false
